docs/README.rst
plone/app/contenttypes/migration/atct_migrator.pt
plone/app/contenttypes/migration/browser.py
plone/app/contenttypes/migration/migration.py
plone/app/contenttypes/migration/utils.py

Migrate images from collective.contentleadimage

---

buildout.d/development.cfg
buildout.d/versions.cfg
docs/README.rst
setup.py

cc @ebrehault @vangheem @pbauer 
@ebrehault you should not use master but 1.1x on plone4.

fix requirement

---

plone/app/contenttypes/profiles/default/types.xml

Also remove old Criteria types if they exist (used in Topics). 

---

plone/app/contenttypes/migration/browser.py
plone/app/contenttypes/migration/configure.zcml
plone/app/contenttypes/migration/migration.py
plone/app/contenttypes/migration/topics.py
plone/app/contenttypes/migration/utils.py
plone/app/contenttypes/tests/test_migration.py
plone/app/contenttypes/tests/test_migration_custom.py
setup.py

- replace ReferenceMigrator and helpers with new methods run before and after a migration
- add @@export_all_relations to export all relations as json

Fix referencemigration

---

plone/app/contenttypes/migration/topics.py
plone/app/contenttypes/tests/test_migration_topic.py

@pbauer Fixed the migrations to work with the changes made in plone/plone.app.querystring#39

Fix ATTopic migration to work with latest changes in plone.app.querystring

---

plone/app/contenttypes/migration/utils.py
plone/app/contenttypes/testing.py
plone/app/contenttypes/tests/test_migration.py

This is part of the Linkintegrity-PLIP https://github.com/plone/Products.CMFPlone/issues/698
Only merge together with plone/plone.app.linkintegrity#22 and its other dependencies.

Linkintegrity

---

docs/CHANGES.rst
docs/README.rst
plone/app/contenttypes/content.py
plone/app/contenttypes/tests/test_collection.py
setup.py

Add getRawQuery method to Collection content type for backward compatibility with Archetypes API

---

plone/app/contenttypes/behaviors/configure.zcml

see plone/plone.app.contenttypes#298

PR: move leadimage to AboveContentTitle

---

plone/app/contenttypes/indexers.py

indexer for getIcon:
when container has Image but contents dont contents aquired image from container
fixed with aq_base ,,,,

fixed aquisition error in indexers.py for getIcon

---

CHANGES.rst
plone/app/contenttypes/setuphandlers.py
plone/app/contenttypes/tests/test_content_profile.py

Should be merged together with pull requests in other packages.
Central issue: https://github.com/plone/Products.CMFPlone/issues/1040

Create standard news/events collections with selection.any.

---

CHANGES.rst
plone/app/contenttypes/indexers.py
plone/app/contenttypes/tests/test_indexes.py

Fixes https://github.com/plone/plone.app.contenttypes/issues/194

Index subject field on the catalog so that is searchable

---

CHANGES.rst
plone/app/contenttypes/migration/utils.py

fix issue in migration where source or target uuid could not be found

---

docs/CHANGES.rst
plone/app/contenttypes/browser/folder.py
plone/app/contenttypes/browser/templates/newsitem.pt

same as https://github.com/plone/plone.app.contenttypes/pull/308

Change all text getters to output_relative_to (backport of 0f5c603f)

---

plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot

@vangheem 
This fixes both test scenarios for me.

Fixed robot tests to work with new querystring changes

---

plone/app/contenttypes/migration/utils.py

Sorry, but I made a little error
if not acc.filename:
is equivalent to 
if getattr(acc, 'filename', None) is None:
And I added `is not None` in my last PR.
I will make the a PR for master branch today.

Typo error

---

CHANGES.rst
plone/app/contenttypes/migration/utils.py

Where PR as ask here: https://github.com/plone/plone.app.contenttypes/pull/323

Fix leadimage migration with no image in field

---

docs/CHANGES.rst
plone/app/contenttypes/configure.zcml

Include explicitly plone.app.event dependency

---

docs/CHANGES.rst
plone/app/contenttypes/migration/custom_migration.py
plone/app/contenttypes/migration/migration.py
plone/app/contenttypes/migration/utils.py

Hi @pbauer @thet 
Here are some fixes I needed to do while migrating a custom contenttype.
To me these fixes are harmless, I am not completely sure about the portlets migration fix...
Could anybody review this?
Thank you!
Gauthier

Various fixes when migrating custom contenttypes

---

CHANGES.rst
plone/app/contenttypes/migration/custom_migration.py
plone/app/contenttypes/migration/migration.py
plone/app/contenttypes/migration/utils.py

For the master, see https://github.com/plone/plone.app.contenttypes/pull/333
Thank you!
Gauthier

Various fixes while migrating custom contenttypes

---

CHANGES.rst
plone/app/contenttypes/content.py
plone/app/contenttypes/tests/test_webdav.py

It fixes https://github.com/plone/Products.CMFPlone/issues/1237
The implementation is quite simple and straightforward (I just override the appropriate `plone.dexterity` webdav methods), but I would appreciate a code review.

Webdav support for File and Image

---

plone/app/contenttypes/behaviors/configure.zcml

See also https://github.com/plone/plone.app.dexterity/pull/208

assign shortnames to behaviors as supported by plone.behavior

---

CHANGES.rst
plone/app/contenttypes/migration/browser.py
plone/app/contenttypes/tests/test_migration.py

Select all types in migration-form by default

---

CHANGES.rst
plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot
plone/app/contenttypes/tests/test_robot.py

This is an annoying test which needs some love. Anyway, this bugs us for too long, so mark as unstable.

Mark robot test as unstable

---

CHANGES.rst
plone/app/contenttypes/indexers.py

fix value/mimetype inconsistency (see #357)

---

docs/CHANGES.rst
plone/app/contenttypes/indexers.py

1.1.x fix value/mimetype inconsistency (see #357)

---

CHANGES.rst
plone/app/contenttypes/browser/templates/link.pt

Show message for editors when viewing Link.

---

CHANGES.rst
plone/app/contenttypes/indexers.py

fix for https://github.com/plone/Products.CMFPlone/issues/1844

fix SearchableText indexer

---

CHANGES.rst
plone/app/contenttypes/profiles/default/types/File.xml

See issue 378: https://github.com/plone/plone.app.contenttypes/issues/378

update File.xml view action url_expr to append /view

---

CHANGES.rst
plone/app/contenttypes/behaviors/leadimage.pt
plone/app/contenttypes/browser/templates/listing.pt
plone/app/contenttypes/browser/templates/listing_album.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt
plone/app/contenttypes/tests/robot/test_folderlisting.robot
setup.py

https://github.com/plone/Products.CMFPlone/issues/1483

Plip 1483 retina image scales

---

CHANGES.rst
plone/app/contenttypes/indexers.py
plone/app/contenttypes/indexers.zcml

https://github.com/plone/Products.CMFPlone/issues/1995

new catalog metadata column: mime_type

---

CHANGES.rst
plone/app/contenttypes/content.py
plone/app/contenttypes/tests/test_behaviors_collection.py
plone/app/contenttypes/tests/test_behaviors_leadimage.py
plone/app/contenttypes/tests/test_behaviors_richtext.py
plone/app/contenttypes/tests/test_behaviors_table_of_contents.py
plone/app/contenttypes/tests/test_collection.py
plone/app/contenttypes/tests/test_collection_rss.py
plone/app/contenttypes/tests/test_content_profile.py
plone/app/contenttypes/tests/test_document.py
plone/app/contenttypes/tests/test_event.py
plone/app/contenttypes/tests/test_file.py
plone/app/contenttypes/tests/test_folder.py
plone/app/contenttypes/tests/test_image.py
plone/app/contenttypes/tests/test_indexes.py
plone/app/contenttypes/tests/test_link.py
plone/app/contenttypes/tests/test_migration.py
plone/app/contenttypes/tests/test_migration_browser.py
plone/app/contenttypes/tests/test_migration_custom.py
plone/app/contenttypes/tests/test_news_item.py
plone/app/contenttypes/tests/test_setup.py
plone/app/contenttypes/tests/test_upgrade.py
plone/app/contenttypes/tests/test_upgrades_migrate_to_pa_event.py
plone/app/contenttypes/tests/test_webdav.py

see https://github.com/plone/Products.CMFPlone/issues/1882

remove unittest2

---

CHANGES.rst
plone/app/contenttypes/indexers.py
plone/app/contenttypes/indexers.zcml
plone/app/contenttypes/profiles/default/metadata.xml
plone/app/contenttypes/tests/test_indexes.py
plone/app/contenttypes/upgrades.py
plone/app/contenttypes/upgrades.zcml

Included upgrade step to reindex the SearchableText index for existing Collections.
Fixes https://github.com/plone/plone.app.contenttypes/issues/406 for Plone 5.1.

Made sure the text field of Collections is searchable. [master]

---

plone/app/contenttypes/behaviors/thumb_icon.py
plone/app/contenttypes/browser/folder.py
plone/app/contenttypes/browser/templates/listing.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt

Followup of https://github.com/plone/Products.CMFPlone/issues/1734

Cleanup of PLIP #1734

---

CHANGES.rst
plone/app/contenttypes/browser/templates/listing.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt

fixing https://github.com/plone/Products.CMFPlone/issues/2077, compiled resources, ...
please merge al related prs together

fixing https://github.com/plone/Products.CMFPlone/issues/2077

---

CHANGES.rst
docs/README.rst
plone/app/contenttypes/indexers.py
plone/app/contenttypes/migration/browser.py
plone/app/contenttypes/migration/migration.py
plone/app/contenttypes/migration/utils.py

Fix some issues encountered during migrations

---

CHANGES.rst
setup.py

Related to https://github.com/plone/Products.CMFPlone/issues/2104

Remove plone.app.robotframework 'reload' extra

---

CHANGES.rst
plone/app/contenttypes/migration/migration.py

Fixes issue 444 but also default_page problems found. Needs backport to 1.1.x as well.

Fix folder layout property migration

---

docs/README.rst

In a training session, both I and the developer I was training found this paragraph not only confusing but misleading.

Docs: Clarify design decisions commentary

---

news/480.bugfix
plone/app/contenttypes/behaviors/configure.zcml

Depends on plone/plone.behavior#19 [MERGED]
Follows #480

Declare the former name of the LeadImage behavior

---

news/511.bugfix
plone/app/contenttypes/tests/robot/test_folderlisting.robot

See https://github.com/plone/Products.CMFPlone/issues/2772

fix test after dropdown-navigation was enabled for new sites

---

news/514.bugfix
plone/app/contenttypes/browser/templates/listing_summary.pt

Add content-core macro to summary_view.pt

---

news/517.bugfix
plone/app/contenttypes/browser/templates/file.pt
plone/app/contenttypes/browser/templates/full_view.pt
plone/app/contenttypes/browser/templates/image.pt
plone/app/contenttypes/browser/templates/link.pt
plone/app/contenttypes/browser/templates/listing.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt
plone/app/contenttypes/browser/templates/newsitem.pt
plone/app/contenttypes/migration/atct_migrator.pt
plone/app/contenttypes/migration/atct_migrator_results.pt
plone/app/contenttypes/migration/custom_migration.pt
plone/app/contenttypes/migration/pac_installer.pt

speed up traversal by making that explicit.

main_template is a browser-view

---

CHANGES.rst
news/522.bugfix
news/524.feature
plone/app/contenttypes/browser/collection.py
plone/app/contenttypes/browser/folder.py
plone/app/contenttypes/browser/templates/listing_album.pt
plone/app/contenttypes/tests/robot/test_folderlisting.robot

Ref.: https://github.com/plone/plone.app.contenttypes/pull/499

Support ILeadImage behavior when display collections

---

news/531.bugfix
plone/app/contenttypes/migration/dxmigration.py

needed for Plone/plone.dexterity#114

proactive clear schema cache to avoid side effects with cached ftis

---

news/3021.bugfix
plone/app/contenttypes/content.py
plone/app/contenttypes/tests/test_security.py

See https://plone.org/security/hotfix/20200121/privilege-escalation-for-overwriting-content

Integrate PloneHotFix20200121: add more permission checks. [maurits]

---

news/554.bugfix
plone/app/contenttypes/browser/templates/image.pt

Display the image size rounded with 1 decimal digit

---

news/560.bugfix
plone/app/contenttypes/browser/templates/listing.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt

This fixes https://github.com/plone/plone.app.contenttypes/issues/560

Avoid doing the search twice in listings by reusing the batch variable

---

news/567.bugfix
plone/app/contenttypes/migration/migration.py

assume is_folderish being false

In the edge case where the meta_type could not be resolved 

---

news/573.bugfix
plone/app/contenttypes/tests/test_collection.py
plone/app/contenttypes/tests/test_document.py
plone/app/contenttypes/tests/test_event.py
plone/app/contenttypes/tests/test_file.py
plone/app/contenttypes/tests/test_folder.py
plone/app/contenttypes/tests/test_image.py
plone/app/contenttypes/tests/test_link.py
plone/app/contenttypes/tests/test_news_item.py

Refs #573 - Make tests more generic

---

news/596.bugfix
plone/app/contenttypes/browser/templates/document.pt

Failsafe condition in document.pt

---

plone/app/contenttypes/browser/link_redirect_view.py

url is a string, so it is not callable

---

setup.py

Ran black on setup.py as test for mr.roboto.
On video call with @gforcada @ale-rt @fredvd now.

black setup.py. Test for mr.roboto.

---

news/609.bugfix
setup.py

Remove cyclic dependency with Products.CMFPlone.

---

news/627.bugfix
plone/app/contenttypes/browser/templates/listing_tabular.pt

Fix author URL in tabular view

---

news/2780.feature
plone/app/contenttypes/behaviors/richtext.py
plone/app/contenttypes/profiles/default/types/Event.xml

Part of PLIP https://github.com/plone/Products.CMFPlone/issues/2780

Add plone.textindexer to event and make 'text' in RichText searchable

---

news/3535.bugfix
plone/app/contenttypes/behaviors/leadimage.pt
plone/app/contenttypes/browser/templates/image.pt
plone/app/contenttypes/browser/templates/listing_album.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/tests/test_image.py

See https://github.com/plone/Products.CMFPlone/issues/3535

When using images view, call tag directly.

---

news/655.news
plone/app/contenttypes/browser/templates/listing_album.pt
plone/app/contenttypes/browser/templates/listing_summary.pt
plone/app/contenttypes/browser/templates/listing_tabular.pt

add loading='lazy' to img tag in listing album and summary

Lazy loading listing

---

news/fix-test_behaviors_table_of_contents.bugfix
plone/app/contenttypes/tests/test_behaviors_table_of_contents.py

The attribute order changed in the HTML, so test need adaption. Also minor cleanup of odds inside test.

fix and cleanup test_behaviors_table_of_contents

---

.gitignore
news/626.bugfix
plone/app/contenttypes/browser/link_redirect_view.py
plone/app/contenttypes/tests/test_link.py

extends the the calculation of url if resolveuid part of link in LinkRedirectView

1letter/fix #626

---

CHANGES.rst
docs/README.rst
news/681.bugfix
plone/app/contenttypes/behaviors/viewlets.py
plone/app/contenttypes/indexers.py

... these are some coincidentally grep/rg findings.

Fix ILeadImageBehavior and IRichTextBehavior interfaces were the name change was forgotten.

---

news/712.bugfix
plone/app/contenttypes/browser/link_redirect_view.py
plone/app/contenttypes/utils.py

Apply https://github.com/plone/plone.app.contenttypes/pull/711 to Plone 6.0.X too

fix use of relative urls in replace_link_variables_by_paths and in the Link view

---

news/4126.bugfix
plone/app/contenttypes/setuphandlers.py
plone/app/contenttypes/tests/robot/variables.py

See https://github.com/plone/Products.CMFPlone/issues/4126

Replace pkg_resources

---

news/4126.bugfix
plone/app/contenttypes/setuphandlers.py
plone/app/contenttypes/tests/robot/variables.py
pyproject.toml

fix: replace pkg_resources with importlib
