plone/plone.app.contenttypes

docs/CHANGES.rst, plone/app/contenttypes/browser/templates/image_view_fullscreen.pt
see https://github.com/plone/Products.CMFPlone/pull/407
Google complains loudly about this template, and will deduct mobile karma points.
Also, using a different `viewport` meta directive than sunburst's default, for better accessibility.
See: https://github.com/plone/Products.CMFPlone/issues/389
=> Update image_view_fullscreen.pt for mobile friendliness

docs/CHANGES.rst, plone/app/contenttypes/browser/collection.py, plone/app/contenttypes/browser/folder.py
This allows the contentFilter dictionary on a request to narrow down listings
=> Fix ``contentFilter`` for collections.

docs/CHANGES.rst, plone/app/contenttypes/upgrades.py
=> Keep additional view_methods when migrating to new view_methods

docs/CHANGES.rst, plone/app/contenttypes/browser/templates/image.pt, plone/app/contenttypes/browser/templates/newsitem.pt
No html5 containers for Plone 4 compatibility. plonetheme.sunburst css selectors don't support figure yet in for example newsitem styling.
=> Don't use <figure> and <figcaption> html5

CHANGES.rst, plone/app/contenttypes/browser/folder.py, plone/app/contenttypes/tests/test_folder.py
In ``FolderView`` based views, don't include the ``portal_types`` query, if ``object_provides`` is set in the ``results`` method keyword arguments. Fixes a case, where no Album Images were shown, when portal_state's ``friendly_types`` didn't include the ``Image`` type.
=> FolderView results fix

docs/CHANGES.rst, plone/app/contenttypes/browser/folder.py, plone/app/contenttypes/tests/test_folder.py
In ``FolderView`` based views, don't include the ``portal_types`` query, if ``object_provides`` is set in the ``results`` method keyword arguments. Fixes a case, where no Album Images were shown, when portal_state's ``friendly_types`` didn't include the ``Image`` type.
=> FolderView results fix for Branch 1.1.x

CHANGES.rst, docs/README.rst, plone/app/contenttypes/content.py, plone/app/contenttypes/tests/test_collection.py, setup.py
=> Add getRawQuery method to Collection content type for backward compatibility with Archetypes API

CHANGES.rst, docs/README.rst, plone/app/contenttypes/migration/migration.py, plone/app/contenttypes/tests/test_migration_custom.py
This allows developers to use the code in custom-migration to migrate arbitrary types and fields using custom field-migrators. This is especially useful when using custom or rare field-types or when you want to migrate fields that are usually not migrateable without additional transforms. 
Here is an example where this is used to migrate a Richtext-Field into a Tuple-Field by passing the custom field-migrator ``some_field_migrator``. Is such a custom migrator you can do just about anything you wish. 
Additionaly you can overwrite the mapping from ``plone.app.contenttypes.migration.field_migrators.FIELDS_MAPPING`` to add or replace migrators for specific field-types.
```python
from plone.app.contenttypes.migration.migration import migrateCustomAT
def some_field_migrator(src_obj, dst_obj, …
```
=> Allow to pass custom field migrators to a custom migration

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/tests/test_indexes.py
Do a ``IRichText`` text indexing on all registered SearchableText indexers by doing it as part of the base ``SearchableText`` function. Convert the text from the source mimetype to ``text/plain``.
=> IRichText indexing for all and html to plain transform

plone/app/contenttypes/browser/templates/listing.pt
the last  fix made robot happy, but supressed the thumbs in standardview (..listing.pt). Now all should be happy. I'll merge this myself when alltests green.
(relates still to https://github.com/plone/Products.CMFPlone/issues/1226)
=> fix listing.pt

CHANGES.rst, plone/app/contenttypes/migration/migration.py
This is what I got when migrating a site from Plone 4.0.10
2015-11-18T11:39:48 ERROR ATCT.migration Failed migration for object /Plone/developer/presentations (Folder -> Folder)
Traceback (most recent call last):
File "/opt/plone/eggs/Products.contentmigration-2.1.11-py2.7.egg/Products/contentmigration/basemigrator/walker.py", line 192, in migrate
migrator.migrate()
File "/opt/plone/eggs/Products.contentmigration-2.1.11-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 220, in migrate
method()
File "/opt/plone/eggs/plone.app.contenttypes-1.2.4-py2.7.egg/plone/app/contenttypes/migration/migration.py", line 201, in last_migrate_layout
getattr(self.old, 'default_page')
AttributeError: default_page
=> Avoid AttributeError when trying to get the default_page of an item when migrating

CHANGES.rst, plone/app/contenttypes/tests/robot/keywords.txt
Simplify keyword in robot framework tests which fails in its newer version.
http://jenkins.plone.org/job/pull-request-5.0/703/robot/report/robot_log.html#s1-s27-t1
=> Changes needed in order to use newer robotframework.

plone/app/contenttypes/testing.py, plone/app/contenttypes/tests/test_collection.py, plone/app/contenttypes/tests/test_file.py, plone/app/contenttypes/tests/test_migration.py
``PLONE_APP_CONTENTTYPES_FIXTURE`` is used by many packages as a base to test against dexterity-types. But the test-setup of p.a.c. has grown historically and contains some useless things that might produce issues with other tests and with test-isolation. These commits try to simplify the test-setup and make it follow best-practices.
Do not merge yet.
=> Simplify test-setup of p.a.c

buildout.cfg, docs/CHANGES.rst, plone/app/contenttypes/migration/utils.py
Check if there is an image into leadimage field for migration.
At the moment, migration will add an `None` image if some object have old `collective.contentleadimage` field with no image registered in that field.
And after migration, we obviously have some errors when we try to get leadimage :
AttributeError: 'NoneType' object has no attribute 'tag' 
I would like to make a test for this, but for that I have to add dependency with collective.contentleadimage. And I think we don't want to have this dependency.
=> Fix leadimage migration for 1.1.x

plone/app/contenttypes/tests/test_document.py
Doing transaction commits on integration layers breaks test isolation.
Fixes:
https://github.com/plone/plone.app.contenttypes/issues/326
=> Fix test isolation problems

CHANGES.rst, plone/app/contenttypes/tests/robot/keywords.txt
This test was looking for a section with an id, but we should just look for an id.
There is a pull request in CMFPlone for changing the section back to a div,
and the tests would fail if that gets merged.
See https://github.com/plone/Products.CMFPlone/issues/1431
This pull request is part of https://github.com/plone/Products.CMFPlone/issues/1430
=> Made xpath expression in test less restrictive.

CHANGES.rst, plone/app/contenttypes/utils.py
Don't fail for ``utils.replace_link_variables_by_paths``, if value is ``None``.
The value can be ``None`` when creating a ``Link`` type with ``invokeFactory`` without ``remoteUrl`` set and calling the indexer before setting the URL.
Was the case for a custom type using ``<property name="klass">plone.app.contenttypes.content.Link</property>`` in the FTI but not for using the ``Link`` type directly. Both were created with transmogrifier without a ``remoteUrl`` set, which is set afterwards by ``transmogrify.dexterity.schemaupdater`` blueprint.
=> Don't fail replace_link_variables_by_paths with empty value

CHANGES.rst, plone/app/contenttypes/tests/robot/keywords.txt, plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot
Especially the relative path criterion sometimes failed on Jenkins during this test:
And the collection should not contain 'Document outside Folder'
For example: http://jenkins.plone.org/job/plone-5.1-python-2.7-robot/293/
Locally for me, it *always* failed.  When debugging, it appeared that the addition of the relative path criterion did not finish before clicking Save.
The absolute path criterion test usually passed, and this was likely because this had a pause of one second before clicking save on the collection edit form.  But this sometimes failed too, at least locally.
Solution is now to always do this:
- pause half a second
- change the focus (we choose the 'Sort reversed' checkbox)
- pause another half second
- then click Save
This does the trick locally, and hopefully on Jenkins …
=> Fixed unstable robot test for location criterion.

CHANGES.rst, plone/app/contenttypes/browser/collection.py
this also has side effects on subclassed collection implementations.
=> deferred initialize to reduce costs of adapter lookup.

CHANGES.rst, plone/app/contenttypes/browser/link_redirect_view.py
This is to make sure url can be converted to string lower in the stack. If not you can get errors like:
Traceback (innermost last): 
Module ZPublisher.Publish, line 138, in publish 
Module ZPublisher.mapply, line 77, in mapply 
Module ZPublisher.Publish, line 48, in call_object 
Module plone.app.contenttypes.browser.link_redirect_view, line 56, in __call__ 
Module ZPublisher.HTTPResponse, line 609, in redirect 
Module ZPublisher.HTTPResponse, line 331, in setHeader 
Module ZPublisher.HTTPResponse, line 134, in _scrubHeader 
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 37: ordinal not in range(128)
=> Encode the absolute_target_url as utf-8 string

CHANGES.rst, plone/app/contenttypes/tests/robot/keywords.txt
Yes, it is annoying to wait longer, and should not be needed, or there should be better ways.
But to me it is far more annoying to have unrelated pull requests tests fail because of timing issues.  Not only on Jenkins: I sometimes have failures locally.
Sample Jenkins failure: http://jenkins.plone.org/job/pull-request-5.0/1215/
I have the feeling that pull requests suffer more from this than the normal tests, which are more split out over various jobs, but that is just a feeling.
=> Wait longer to fix unstable robot tests.

CHANGES.rst, plone/app/contenttypes/profiles/default/types/Collection.xml, plone/app/contenttypes/profiles/default/types/Document.xml, plone/app/contenttypes/profiles/default/types/Event.xml, plone/app/contenttypes/profiles/default/types/File.xml, plone/app/contenttypes/profiles/default/types/Folder.xml, plone/app/contenttypes/profiles/default/types/Image.xml, plone/app/contenttypes/profiles/default/types/Link.xml, plone/app/contenttypes/profiles/default/types/News_Item.xml
configure action edit urls to not be available, when item is locked - as it is recommended here: https://github.com/plone/plone.app.lockingbehavior/blob/master/README.rst
also, add ``i18n:attribute="title"`` to all action nodes.
i guess it is, but i'm not sure if it is necessary. it doesn't hurt at least....
when this is going to be answered, i can also add locking support to other types: 
https://github.com/plone/plone.app.contenttypes/issues/358
/cc @jensens @pbauer @vangheem
=> configure edit urls for locking support

CHANGES.rst, plone/app/contenttypes/behaviors/collection.py
Remove ``path`` index injection in "plone.collection" behaviors ``results`` method.
It is a duplicate. Exactly the same is done already in the ``plone.app.querybuilder.querybuilder._makequery``,  which is called by above ``results`` method.
see https://github.com/plone/plone.app.querystring/blob/master/plone/app/querystring/querybuilder.py#L110-L120
=> remove dup path injection code in collections results method

CHANGES.rst, plone/app/contenttypes/tests/robot/keywords.txt, plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot
This needs further investigation, but must not block Plone development.
I tried fixing it too in this pull request, and *maybe* it has become more stable. But locally on Plone 5.1 with Firefox 46.0.1 I still see sometimes a failure, sometimes a success.
See for example http://jenkins.plone.org/job/plone-5.1-python-2.7-robot/671/robot/
Issue for fixing this and another unstable test: https://github.com/plone/plone.app.contenttypes/issues/362
=> Marked relative location criterion robot test as unstable.

CHANGES.rst, plone/app/contenttypes/browser/utils.py
with the removal of the skins folder in https://github.com/plone/Products.MimetypesRegistry/pull/8/commits/61acf8327e5c844bff9e5c5676170aaf0ee2c323 we need the full resourcepath now
=> Fix Mimetype icon path

CHANGES.rst, plone/app/contenttypes/migration/field_migrators.py
I got UnicodeEncodeError when migrating unicode filenames. This is the error:
```
>>> var = u'\xf3'
>>> print var
ó
>>> "%s"%var
u'\xf3'
>>> "{0}".format(var)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 0: ordinal not in range(128)
>>> u"{0}".format(var)
u'\xf3'
>>> print u"{0}".format(var)
ó
```
=> String needs to be unicode when format parameter is unicode

CHANGES.rst, buildout.cfg, plone/app/contenttypes/browser/folder.py, plone/app/contenttypes/browser/templates/listing.pt
This PR optimizes the default (folder) listing templates.
Previously all objects were awakend from the catalog. Now this is only done for events. It seems to be needed for some date math.
=> Optimize listing

CHANGES.rst, buildout.cfg, plone/app/contenttypes/browser/folder.py, plone/app/contenttypes/browser/templates/listing.pt
Reverts plone/plone.app.contenttypes#386
keep obj, other views rely on it
adding a nocall: to the define should help and not cause problems with other usecases
=> Revert "Optimize listing"

docs/CHANGES.rst, plone/app/contenttypes/migration/migration.py
Add condition so custom folder migration does not fail if there is not an 'excludeFromNav'
=> Prevent custom folder migration from failing

CHANGES.rst, plone/app/contenttypes/browser/collection.py
Traditionally it has been possible to customize collection search with contentFilter request parameter. This is based on ZServer HTTPRequest demarshalling query string into contentFilter dictionary. For example:
contentFilter.portal_type:list:record=Image
would be parsed into request.form['contentFilter'] as
{"portal_type": ["Image"]}
and would restrict collection to only display images (unless content_type criteria was already defined in collection).
This almost worked already, but didn't because HTTPRequest does seem to return some kind of dict like wrapper instead of real dictionary, resulting ``update`` method being missing attribute. This is fixed by this pull by enforcing contentFilter read from request to be real dictionary.
=> Fix issue where contentFilter could not be read from request

CHANGES.rst, plone/app/contenttypes/content.py
@jensens @fgrcon i had to keep the ``content_type`` as method, as this was added here a year ago:
https://github.com/plone/plone.app.contenttypes/commit/1b6c75dae22cee9ad13b99fb013cd02189ff2d9a
I thought, that was done with latest @fgrcon PR, but it wasn't.
however, with the getattr call, the plone.app.upgrade step shouldn't fail anymore.
=> Make content_type a property and do not fail if image/file is None

CHANGES.rst, plone/app/contenttypes/browser/utils.py
Version 1.2.19 introduced a change to fit Products.MimetypesRegistry 2.1, but Plone 5.0 should remain on 2.0.x.
Fixes https://github.com/plone/Products.CMFPlone/issues/1997.
Revert "with the removal of the skins folder in https://github.com/plone/Products.MimetypesRegistry/pull/8/commits/61acf8327e5c844bff9e5c5676170aaf0ee2c323 we need the full resourcepath now"
This reverts commit 292aefd647a67d6d0767aba39a687845fab00a76.
=> Fixed Mimetype icon path. [1.2.x, Plone 5.0]

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/indexers.zcml, plone/app/contenttypes/profiles/default/metadata.xml, plone/app/contenttypes/tests/test_indexes.py, plone/app/contenttypes/upgrades.py, plone/app/contenttypes/upgrades.zcml
Includes upgrade step to reindex the SearchableText index for existing Collections.
Fixes https://github.com/plone/plone.app.contenttypes/issues/406 for Plone 4.3.
=> Made sure the text field of Collections is searchable. [1.1.x]

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/indexers.zcml, plone/app/contenttypes/profiles/default/metadata.xml, plone/app/contenttypes/tests/test_indexes.py, plone/app/contenttypes/upgrades.py, plone/app/contenttypes/upgrades.zcml
Includes upgrade step to reindex the SearchableText index for existing Collections.
Fixes https://github.com/plone/plone.app.contenttypes/issues/406 for Plone 5.0.
=> Made sure the text field of Collections is searchable. [1.2.x]

CHANGES.rst, plone/app/contenttypes/tests/test_document.py, plone/app/contenttypes/tests/test_news_item.py
Calling @@view on a document or news item does not correctly show the body text.
You get this: `RichTextValue object. (Did you mean .raw or .output?)`
This is because @@view uses a standard item.pt template from plone.app.dexterity.
Instead, these tests should use the default browser views defined in the profile.
Then the text is properly displayed.
=> Fixed two failing unit tests.

plone/app/contenttypes/behaviors/thumb_icon.py
see https://github.com/plone/plone.app.contenttypes/pull/410 
no changelog entry!
=> further fixes for plip 1734-attribute-renames

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/profiles/default/metadata.xml, plone/app/contenttypes/tests/test_indexes.py, plone/app/contenttypes/upgrades.py, plone/app/contenttypes/upgrades.zcml
This avoids a double transform (raw source to output mimetype to plain text).
Includes a reindex of the SearchableText index for Collections, Documents and News Items.
Issue https://github.com/plone/Products.CMFPlone/issues/2066
Should be done for other branches too, but let's first see if this gets approved.
=> Use original raw text and mimetype when indexing rich text. [master]

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/profiles/default/metadata.xml, plone/app/contenttypes/tests/test_indexes.py, plone/app/contenttypes/upgrades.py, plone/app/contenttypes/upgrades.zcml
This avoids a double transform (raw source to output mimetype to plain text).
Includes a reindex of the SearchableText index for Collections, Documents and News Items.
Backported from master.
Issue https://github.com/plone/Products.CMFPlone/issues/2066
=> Use original raw text and mimetype when indexing rich text. [1.2.x]

CHANGES.rst, plone/app/contenttypes/indexers.py, plone/app/contenttypes/profiles/default/metadata.xml, plone/app/contenttypes/tests/test_indexes.py, plone/app/contenttypes/upgrades.py, plone/app/contenttypes/upgrades.zcml
This avoids a double transform (raw source to output mimetype to plain text).
Includes a reindex of the SearchableText index for Collections, Documents and News Items.
Backported from master
Issue https://github.com/plone/Products.CMFPlone/issues/2066
=> Use original raw text and mimetype when indexing rich text. [1.1.x]

CHANGES.rst, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/migration/migration.py, plone/app/contenttypes/migration/patches.py
This disables queuing of indexing-operations during migration to Dexterity to prevent catalog-errors. 
Here is example traceback:
(...)
Module plone.app.contenttypes.migration.browser, line 227, in __call__
Module plone.app.contenttypes.migration.topics, line 702, in migrate_topics
Module Products.contentmigration.basemigrator.walker, line 144, in go
Module Products.contentmigration.basemigrator.walker, line 177, in migrate
Module Products.contentmigration.walker, line 64, in walk
Module Products.ZCatalog.CatalogBrains, line 93, in getObject
Module Products.ZCatalog.CatalogBrains, line 57, in getPath
Module Products.ZCatalog.ZCatalog, line 518, in getpath
KeyError: 487546660
Also: 
* move all patches to a separate method
* use the same patches for custom migrations
=> Add patch of catalog optimization during migrations to DX 

CHANGES.rst, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/migration/dxmigration.py, plone/app/contenttypes/migration/utils.py
As refered in this issue for plone app multilingual : https://github.com/plone/plone.app.multilingual/issues/226
These 2 variables :
- plone.app.contenttypes.migration.utils.HAS_MULTILINGUAL becomes plone.app.contenttypes.migration.utils.HAS_LINGUA_PLONE
- Products.contentmigration.common.HAS_LINGUA_PLONE
only check if LinguaPlone is installed
I'm willing to write tests too, but I don't know who to write it, in plone app contenttypes ? in plone app multilingual ?
(This PR is also related to this https://github.com/plone/Products.contentmigration/pull/9)
=> Fix multilingual empty view

plone/app/contenttypes/setuphandlers.py
When importing my integration profile in the ZMI, i get the following error - this PR fixes it for me. I don't know, if there are situations, where ```getSite``` fails... I don't think it would.
```
2017-09-29 23:15:27 ERROR Zope.SiteErrorLog 1506719727.480.134533008393 http://localhost:8080/Plone/portal_setup/manage_importAllSteps
Traceback (innermost last):
Module ZPublisher.Publish, line 138, in publish
Module ZPublisher.mapply, line 77, in mapply
Module ZPublisher.Publish, line 48, in call_object
Module Products.GenericSetup.tool, line 579, in manage_importAllSteps
Module Products.GenericSetup.tool, line 388, in runAllImportStepsFromProfile
- __traceback_info__: profile-bda.aaf.site:default
Module Products.GenericSetup.tool, line 1433, in _runImportStepsFromContext
Module …
```
=> fix retrieving of portal object in setuphandlers

CHANGES.rst, plone/app/contenttypes/schema/link.xml, plone/app/contenttypes/tests/test_link.py
Otherwise, the new link widget resolves that to the portal root object.
Also, it's not a valid URL.
Fixes: https://github.com/plone/Products.CMFPlone/issues/2163
The default value also allows that the required field passes the requirement-check - the Link form can just submitted without entering a valid URL.
Instead of the default value, the other PR 76 from plone.app.z3cform adds placeholders for email and external link.
Merge together:
https://github.com/plone/plone.app.contenttypes/pull/431
https://github.com/plone/plone.app.z3cform/pull/76
=> Do not use a default value in the form of ``http://`` for the link.

CHANGES.rst, plone/app/contenttypes/behaviors/tableofcontents.py
Fixes https://github.com/plone/plone.app.contenttypes/issues/37.
=> Remove last use of atcontenttypes translation domain.

CHANGES.rst, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/migration/custom_migration.pt, plone/app/contenttypes/migration/custom_migration.py, plone/app/contenttypes/migration/migration.py, plone/app/contenttypes/migration/patches.py, plone/app/contenttypes/tests/test_migration.py
* Allow to patch searchableText index during migrations
* Expose option to skip catalog-reindex after migration in form
=> Allow patching of searchableText during migrations

CHANGES.rst, plone/app/contenttypes/profiles/default/types.xml, plone/app/contenttypes/profiles/default/types/Plone_Site.xml
We do not need to specify the Plone Site in types.xml, as it already exists.
=> Do not define 'Plone Site' here.

CHANGES.rst, plone/app/contenttypes/profiles.zcml, plone/app/contenttypes/setuphandlers.py
Fixes https://github.com/plone/Products.CMFPlone/issues/2238
=> Rename post_handlers to prevent them to be run as old importSteps. 

CHANGES.rst, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/tests/test_migration.py, plone/app/contenttypes/tests/test_migration_custom.py
Use `get_installer` to check if `plone.app.contenttypes` is installed or installable.
Use `portal_setup` directly for blacklisting the `type_info` step when installing our profile.
=> Do not use `portal_quickinstaller` in the migration form.

CHANGES.rst, plone/app/contenttypes/setuphandlers.py, plone/app/contenttypes/tests/test_content_profile.py
By making the following changes, I have tried to solve issue plone/Products.CMFPlone#2259.
1. Added a changelog entry about the following changes a feature update.
2. Removed the publish method in the setuphandlers.py
3. Fixed the failing test which checks if the members folder is public.
I had a minor doubt regarding the test check. Do I have to remove the following test check or do I have to make a separate method to check if the folder is private?
=> Made members folder private

CHANGES.rst, plone/app/contenttypes/browser/templates/listing.pt, plone/app/contenttypes/browser/templates/listing_tabular.pt, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/migration/custom_migration.py, plone/app/contenttypes/migration/dxmigration.py, plone/app/contenttypes/migration/migration.py, plone/app/contenttypes/migration/utils.py, plone/app/contenttypes/tests/test_folder.py
- In folder listings, when a content object has no title show it's id instead of an empty title.
- Migrations: Try to delete the layout attribute before setting the layout.
Rework parts where the layout is set by always setting the layout.
=> title_or_id fix, layout setting fixes

CHANGES.rst, plone/app/contenttypes/browser/link_redirect_view.py, plone/app/contenttypes/tests/test_link.py
fixes #457 
cc: @plone/framework-team
=> Do not encode query strings on internal link redirections

CHANGES.rst, plone/app/contenttypes/testing.py, plone/app/contenttypes/tests/test_migration.py, plone/app/contenttypes/tests/test_migration_browser.py, plone/app/contenttypes/tests/test_migration_custom.py, plone/app/contenttypes/tests/test_migration_topic.py, plone/app/contenttypes/upgrades.zcml, setup.py
Instead of a hard dependency on Archetypes for tests, skip migration tests unless ATContentTypes is present.
I couldn't think of a more elegant way to set this up, but would be happy for ideas!
=> Only test migration if AT is installed

CHANGES.rst, plone/app/contenttypes/setuphandlers.py
to find the preferred language, instead of using a fallback on the
Plone Site Root's empty language attribute. That probably worked
only  in Plone < 3.
=>  When installing the add'on, use portal_languages tool

CHANGES.rst, plone/app/contenttypes/migration/utils.py
In the case some rules where deleted but there are still assignments in the portal, we should skip the assignment on migration.
=> check if a contentrule exists before assignment on migration

CHANGES.rst, plone/app/contenttypes/migration/browser.py, plone/app/contenttypes/migration/custom_migration.py, plone/app/contenttypes/migration/dxmigration.py, plone/app/contenttypes/migration/migration.py, plone/app/contenttypes/migration/utils.py
backport migration fixes from master for layouts and brain .getObject() failures and layout settings.  These are commits d6e280b80320654d3766c06359b5d1d82853cc5b and 0b1d57800cd91dbe9cf79a74beefefbb00d977fe. 
Ran into these while moving a 4.3.x site to plone.app.contenttypes 1.1.6
=> backport migration fixes from master for layouts and brain .getObject()

CHANGES.rst, plone/app/contenttypes/content.py
The ``Format`` accessor should actually return the ``format`` attribute
(see plone/Products.CMFPlone#2540)
=> Fix the Format accessor

CHANGES.rst, plone/app/contenttypes/content.py, setup.py
The ``Format`` accessor should actually return the ``format`` attribute
(see plone/Products.CMFPlone#2540)
=> Fix the Format accessor (1.2.x)

CHANGES.rst, plone/app/contenttypes/browser/folder.py, plone/app/contenttypes/tests/test_folder.py
Fixes folder view when there is one item more than the batch size.
Closes #500
=> Let folderListing know about the orphan parameter

CHANGES.rst, plone/app/contenttypes/migration/field_migrators.py
If an AT schema had a `BooleanField` that defaults to `True` and an instance
had a value set to `False`, the migration would take that `False` to mean to
leave the value as unset on the new DX instance which would then get the
default `True` value.  Fix this bug by properly handling unset values by
checking for `AttributeError`.
Note that this fix should probably be applied to master and the other active branches.
=> Fix migrating False boolean values, handling of "unset" values:

news/2781.bugfix, plone/app/contenttypes/content.py, plone/app/contenttypes/tests/test_webdav.py
Detect whether a webdav request is RFC822 or pure payload and handle acordingly so that external editor and classic webdav clients are both supported.
Fixes https://github.com/plone/Products.CMFPlone/issues/2781
=> Bring back external editor support

news/2952.bugfix, plone/app/contenttypes/configure.zcml
This is instead of using includeDependencies.
See https://github.com/plone/Products.CMFPlone/issues/2952
=> Explicitly load zcml of dependencies.

news/535.bugfix, plone/app/contenttypes/testing.py
If Products.ATContentTypes is available and plone.app.contenttypes is installed by the addPloneSite method, migration tests will fail.
To solve this, we first uninstalll plone.app.contenttypes durint test setup.
This is a blocker for another [pull request](https://github.com/plone/Products.CMFPlone/pull/2971) on CMFPlone.
=> Migration tests, uninstalls plone.app.contentypes if previously installed.

CHANGES.rst, plone/app/contenttypes/behaviors/richtext.py
@datakurre since version 2.0 the behavior names were renamed. The ``getText`` view for richtext was forgotten. There are not tests and it is not used in plone.app.contenttypes.  From your commit messages ([1], [2]) it looks like "BBB" code.
Should we merge my fix or remove the code?
[1] https://github.com/plone/plone.app.contenttypes/commit/9c40ed0c8ac3b55c62c0422094e188c1dbcfe5cc#diff-c53d5bba65836ce2021029c7829028da
[2] https://github.com/plone/plone.app.contenttypes/commit/62bf3b8d03310889260c07517cbfd06162cd0c99#diff-2f5868c3a427009d74372bcf983693ee
=> Fix richtext getText view to use the correct schema interface.

news/3021.bugfix, plone/app/contenttypes/content.py, plone/app/contenttypes/tests/test_security.py
See https://plone.org/security/hotfix/20200121/privilege-escalation-for-overwriting-content
For Plone 5.1.
Backport from master PR #543.
=> Integrate PloneHotFix20200121: add more permission checks. [1.4.x]

news/3021.bugfix, plone/app/contenttypes/content.py, plone/app/contenttypes/tests/test_security.py
See https://plone.org/security/hotfix/20200121/privilege-escalation-for-overwriting-content
For Plone 4.3.
Backport from branch 1.4.x PR #545.
=> Integrate PloneHotFix20200121: add more permission checks.

news/560.bugfix, plone/app/contenttypes/browser/templates/listing.pt, plone/app/contenttypes/browser/templates/listing_tabular.pt
This fixes https://github.com/plone/plone.app.contenttypes/issues/560
=> Avoid doing the search twice in listings by reusing the batch variable (Plone 4.3)

news/560.bugfix, plone/app/contenttypes/browser/templates/listing.pt, plone/app/contenttypes/browser/templates/listing_tabular.pt
This fixes https://github.com/plone/plone.app.contenttypes/issues/560
=> Avoid doing the search twice in listings by reusing the batch variable (Plone 5.1)

news/569.bugfix, plone/app/contenttypes/browser/utils.py, plone/app/contenttypes/tests/test_browser_utils.py
The contentType of the file was ignored, and icon paths could have a duplicate `++resource++mimetype.icons/`.
Fixes issue #569.
Added tests for the method, using dummy files.
Note that in `test_file.py` there already are indirect tests with real files, checking that a specific [icon is on the rendered page](https://github.com/plone/plone.app.contenttypes/blob/2.1.9/plone/app/contenttypes/tests/test_file.py#L171).
=> Fixed problems in getMimeTypeIcon.

news/572.feature, plone/app/contenttypes/migration/migration.py
This way you can control which objects to migrate.
=> Allow passing a custom catalog-query to migrateCustomAT 

news/582.bugfix, plone/app/contenttypes/migration/migration.py
Fixes https://github.com/plone/plone.app.contenttypes/issues/582
Sample error:
```
2021-01-11 21:30:37,748 ERROR   [ATCT.migration:205][waitress-0] Failed migration for object /minaraad/digibib/meetings/20130507-0 (Meeting -> Meeting)
Traceback (most recent call last):
File "/Users/maurits/shared-eggs/cp27m/Products.contentmigration-2.2.1-py2.7.egg/Products/contentmigration/basemigrator/walker.py", line 194, in migrate
migrator.migrate()
File "/Users/maurits/shared-eggs/cp27m/Products.contentmigration-2.2.1-py2.7.egg/Products/contentmigration/basemigrator/migrator.py", line 220, in migrate
method()
File "/Users/maurits/shared-eggs/cp27m/plone.app.contenttypes-2.2.1-py2.7.egg/plone/app/contenttypes/migration/migration.py", line 191, in migrate_nextprevious
if …
```
=> Catch AttributeError for getNextPreviousEnabled during migration.

news/584.bugfix, plone/app/contenttypes/migration/field_migrators.py
This fixes `AttributeError: 'NoneType' object has no attribute 'asdatetime'`.
Fixes issue #584
=> migrate_datetimefield: do nothing when old value is None.

news/510.bugfix, plone/app/contenttypes/migration/utils.py
- Migrate `relatesTo` AT relation to `relatedItems` DX relation.
- In DX check the schema to see if relation field is list or item.  Taken over from [collective.relationhelpers](https://github.com/collective/collective.relationhelpers).
- `restore_references`: accept `relationship_fieldname_mapping` argument. This must be a dictionary with a relationship name as key and fieldname as value, instead of always using `relatedItems` as fieldname. Fixes https://github.com/plone/plone.app.contenttypes/issues/510
Tried out in a migration from AT 4.3 to DX 5.2.
Note: the migration tests are skipped on Python 3 because they need Archetypes. So I only run one Jenkins job.
=> Various fixes for migration references/relations

plone/app/contenttypes/setuphandlers.py
An upgrade profile was added in PR #590 but was not hidden.
This causes a test in `Products/CMFPlone/controlpanel/tests/test_controlpanel_browser_installer.py` to [fail](https://jenkins.plone.org/job/plone-6.0-python-3.6/226/testReport/junit/Products.CMFPlone.controlpanel.tests.test_controlpanel_browser_installer/AddonsControlPanelFunctionalTest/test_addons_controlpanel_install_and_uninstall_all/).
In `test_addons_controlpanel_install_and_uninstall_all` we unexpectedly find an Uninstall button.
This can be seen when you create a fresh site.  In the Modules control panel you can uninstall plone.app.contenttypes.
Things go rather wrong when you try that. :-)
=> Hide the upgrade profile.

news/611.bugfix, setup.py
No longer needed, since `Products.CMFPlone` explicitly includes our zcml.
=> Removed autoinclude entry point.

news/616.bugfix, plone/app/contenttypes/tests/test_indexes.py
Adapt the tests to cope with the fact the since Plone 6 the Plone site root is cataloged
The following PR should be merged together:
https://github.com/plone/plone.app.content/pull/236
https://github.com/plone/plone.app.contentlisting/pull/39
https://github.com/plone/plone.app.contenttypes/pull/616
https://github.com/plone/plone.app.upgrade/pull/264
https://github.com/plone/plone.restapi/pull/1251
https://github.com/plone/Products.CMFPlone/pull/3343
=> Adapt the tests for Plone 6

news/6.bugfix, plone/app/contenttypes/tests/robot/test_folderlisting.robot
In lots of robot tests we are seeing that you need to:
- focus on an element
- wait until it is visible
- only *then* click on it.
Part of PLIP https://github.com/plone/Products.CMFPlone/issues/3211
=> Fix tests with ES6.

news/106.bugfix, setup.py
See https://github.com/plone/plone.namedfile/issues/106
Also, removed pre-release pinnings from dependencies.
=> Depend on `plone.namedfile` core instead of its empty `[blobs]` extra.

news/1.bugfix, plone/app/contenttypes/behaviors/richtext.py
If a content type has the richtext behavior enabled, but the text field is not mandatory, plone.app.linkintegrity `modifiedContent` event handler will be called and although there (on p.a.linkintegrity) there is already a `getattr`, here in p.a.contenttypes we try to access the attribute without first checking if it exists at all.
This PR tries to handle that.
=> No text attribute

news/3582.bugfix, plone/app/contenttypes/tests/robot/keywords.txt
'Click Button Save' sometimes failed.
See two failures on Jenkins: https://jenkins.plone.org/job/plone-6.0-python-3.9-robot-chrome/1355/robot/
=> Robot tests: use more specific element when clicking Save button.

.coveragerc, .gitignore, .meta.toml, .pre-commit-config.yaml, news/69.tests, plone/app/contenttypes/tests/robot/keywords.txt, plone/app/contenttypes/tests/robot/test_collection_creator_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_review_state_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_short_name_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_type_criterion.robot, plone/app/contenttypes/tests/robot/test_folderlisting.robot, pyproject.toml, setup.cfg, tox.ini
Uses https://github.com/plone/meta/pull/69
I had to change some resources slightly, otherwise they were not found:
```
-Resource  plone/app/contenttypes/tests/robot/keywords.txt
+Resource  keywords.txt
```
For running the tests from the coredev buildout this makes no difference.
Also: in coredev the tests are run with headless Chrome, and here in the package using `tox -e test` they are run with Firefox in the foreground.  I have `ROBOT_BROWSER=headlesschrome` in my environment variables.  So: a bit strange, no idea what causes this difference, but it works.
=> run robot tests on gh-actions

news/679.bugfix, plone/app/contenttypes/browser/templates/listing.pt, plone/app/contenttypes/tests/test_folder.py
=> Fix folder listing template when `plone.eventlocation` behavior is disabled

news/688.bugfix, plone/app/contenttypes/browser/templates/file.pt
=> Support using the file template on objects that have no file attributes.

news/125.bugfix, plone/app/contenttypes/browser/templates/full_view_item.pt, plone/app/contenttypes/setuphandlers.py, setup.py
The ``portal_properties`` tools is deprecated, ``visible_ids`` was not set as real property, and usage of ``visible_ids`` was largely removed in Plone 5.0 already. You already can no longer set ``visible ids`` in the Editing control panel, nor in the member preferences. The only remaining use for ``visible_ids``, if set to true, was to show the page ids on the 'select default page' form.
=> No longer set portal_properties.site_properties.visible_ids on site creation

news/698.tests, plone/app/contenttypes/tests/robot/keywords.robot, plone/app/contenttypes/tests/robot/test_collection_creator_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_location_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_review_state_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_short_name_criterion.robot, plone/app/contenttypes/tests/robot/test_collection_type_criterion.robot, plone/app/contenttypes/tests/robot/test_folderlisting.robot
This is part of https://github.com/plone/Products.CMFPlone/issues/3813
* port robot tests
=> Port robot tests

news/714.bugfix, plone/app/contenttypes/utils.py
=> fix accidental storage with aq wrapper in migrate_base_class_to_new_class
